theme: Slate
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
Gemfile:gem "github-pages", group: :jekyll_plugins
title: [My portfolio]
description: [Alx-se portfolio project]
